apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-replica-3
spec:
  replicas: 1
  selector:
    db: rethinkdb
    role: replica
    instance: three
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replica
        instance: three
    spec:
      containers:
      - image: us.gcr.io/dray-app/rethinkdb:2.3.2
        command:
          - "/usr/bin/run.sh"
          - "--server-name"
          - "replica_3"
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-storage
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: rethinkdb-storage-3
        name: rethinkdb-storage
